=== GinoLigorria/dlc-final-2010/wayraSearch/Indizador_archivos/Lectores.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT lectores (lector+)>
<!ELEMENT lector (tipo+)>
<!ATTLIST lector
          class CDATA #REQUIRED>
<!ELEMENT tipo (#PCDATA)>

=== GinoLigorria/dlc-final-2010/trunk/wayraSearch/Lectores.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lectores SYSTEM "Lectores.dtd">
<lectores>
	<lector class="Lectores.LectorTextoPlano">
		<tipo>txt</tipo>
		<tipo>java</tipo>
		<tipo>nfo</tipo>
		<tipo>rtf</tipo>
		<tipo>c</tipo>
		<tipo>cpp</tipo>
	</lector>
	<lector class="Lectores.Lector">
		<tipo>*</tipo>
	</lector>
</lectores>
